# Allow user to toggle battery charge threshold and set default to 80 on boot
z /sys/class/power_supply/BAT0/charge_control_end_threshold 0666 root root -
w /sys/class/power_supply/BAT0/charge_control_end_threshold - - - - 80

# Allow user to toggle ACPI platform profile (quiet / balanced / performance)
z /sys/firmware/acpi/platform_profile 0666 root root -
z /sys/devices/platform/asus-nb-wmi/throttle_thermal_policy 0666 root root -
