$lock_cmd = pidof hyprlock || hyprlock
$suspend_cmd = systemctl suspend || loginctl suspend

general {
    lock_cmd = $lock_cmd
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
    inhibit_sleep = 3
}

# 1. Idle lock when unlocked
# Inactivity for 300 seconds (5 mins) -> lock screen
listener {
    timeout = 300 # 5 mins
    on-timeout = loginctl lock-session
}

# 2. DPMS off after idle lock
# Inactivity for 450 seconds (7.5 mins total = exactly 2.5 mins after the 5-min idle lock) -> turn off display
listener {
    timeout = 450 # 7.5 mins (2.5 mins after idle lock)
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

# 3. System suspend after 30 mins
listener {
    timeout = 1800 # 30 mins
    on-timeout = $suspend_cmd
}
